# Generated by Django 2.0 on 2018-01-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_uuid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_file',
            field=models.ImageField(upload_to='media/temp-fine-uploader/'),
        ),
    ]
